# TEST PLAYGROUND

In [230]:
import pickle
import myLibrary as mL
import pandas as pd
import numpy as np

from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

DP = mL.DataProcessor

In [231]:
DATAFILE = "GOM_2_A.pickle"
n_steps = 3 #is 3 in example ..

In [232]:
with open(f'data/datasets/type_A/{DATAFILE}', 'rb') as f:
    # load the object from the file using pickle.load()
    dataset = pickle.load(f)

data = dataset["data"]
data

WDIR_42012  WSPD_42012  PRES_42012  ATMP_42012  \
timestamp                                                             
2020-01-01 00:00:00       294.0         5.1      1019.9        14.5   
2020-01-01 01:00:00       292.0         4.7      1020.2        14.7   
2020-01-01 02:00:00       292.0         4.2      1020.6        14.8   
2020-01-01 03:00:00       288.0         4.2      1020.7        15.0   
2020-01-01 04:00:00       300.0         4.6      1020.4        15.0   
...                         ...         ...         ...         ...   
2022-12-31 19:00:00       234.0         1.4      1016.0        18.8   
2022-12-31 20:00:00       190.0         2.5      1015.7        19.3   
2022-12-31 21:00:00       213.0         3.2      1016.0        19.9   
2022-12-31 22:00:00       207.0         2.2      1015.9        20.1   
2022-12-31 23:00:00       201.0         3.1      1016.1        20.4   

                     WTMP_42012  DEWP_42012  WDIR_42040  WSPD_42040  \
timestamp                                                             
2020-01-01 00:00:00        19.1         5.2       297.0         3.9   
2020-01-01 01:00:00        19.1         5.3       306.0         3.6   
2020-01-01 02:00:00        19.0         6.2       314.0         3.5   
2020-01-01 03:00:00        18.9         6.7       340.0         3.3   
2020-01-01 04:00:00        18.8         7.1       296.0         2.8   
...                         ...         ...         ...         ...   
2022-12-31 19:00:00        20.6        17.6       262.0         2.7   
2022-12-31 20:00:00        20.7        18.0       262.0         2.7   
2022-12-31 21:00:00        20.9        18.3       262.0         1.9   
2022-12-31 22:00:00        20.8        18.8       262.0         3.1   
2022-12-31 23:00:00        20.8        19.2       262.0         2.4   

                     PRES_42040  ATMP_42040  ...  WDIR_42003  WSPD_42003  \
timestamp                                    ...                           
2020-01-01 00:00:00      1020.5        15.3  ...        35.0         5.7   
2020-01-01 01:00:00      1021.0        15.5  ...        44.0         5.4   
2020-01-01 02:00:00      1021.1        15.9  ...        47.0         5.4   
2020-01-01 03:00:00      1021.2        16.1  ...        35.0         4.5   
2020-01-01 04:00:00      1021.2        16.1  ...        39.0         4.3   
...                         ...         ...  ...         ...         ...   
2022-12-31 19:00:00      1016.6        21.6  ...        54.0         3.4   
2022-12-31 20:00:00      1016.3        21.5  ...        54.0         3.4   
2022-12-31 21:00:00      1016.4        21.6  ...        54.0         3.4   
2022-12-31 22:00:00      1016.6        21.5  ...        54.0         3.4   
2022-12-31 23:00:00      1016.9        21.3  ...        54.0         3.4   

                     PRES_42003  WTMP_42003  WDIR_42055  WSPD_42055  \
timestamp                                                             
2020-01-01 00:00:00      1019.3        26.8       101.0         4.6   
2020-01-01 01:00:00      1019.5        26.9       101.0         4.6   
2020-01-01 02:00:00      1019.6        26.9       101.0         4.6   
2020-01-01 03:00:00      1020.3        26.9       101.0         4.6   
2020-01-01 04:00:00      1020.2        26.9       101.0         4.6   
...                         ...         ...         ...         ...   
2022-12-31 19:00:00      1012.1        29.4       108.0         2.4   
2022-12-31 20:00:00      1012.1        29.4       114.0         2.0   
2022-12-31 21:00:00      1012.1        29.4       110.0         2.5   
2022-12-31 22:00:00      1012.1        29.4       115.0         3.1   
2022-12-31 23:00:00      1012.1        29.4       114.0         3.5   

                     PRES_42055  ATMP_42055  WTMP_42055  DEWP_42055  
timestamp                                                            
2020-01-01 00:00:00      1011.8        25.6        26.4        23.7  
2020-01-01 01:00:00      1011.8        25.6       

# Test Data

In [233]:
n = 10

data = {}
for col in range(1, 5):
    key = f'WDIR_{col}' if col % 2 != 0 else f'WSPD_{col}'
    data[key] = []

    for row in range(1, n+1):
        value = (row-1) * 4 + col
        data[key].append(value)

timestamps = pd.date_range(start='2020-01-01 01:00:00', periods=n, freq='H')
data = pd.DataFrame(data, index=timestamps)
data

WDIR_1  WSPD_2  WDIR_3  WSPD_4
2020-01-01 01:00:00       1       2       3       4
2020-01-01 02:00:00       5       6       7       8
2020-01-01 03:00:00       9      10      11      12
2020-01-01 04:00:00      13      14      15      16
2020-01-01 05:00:00      17      18      19      20
2020-01-01 06:00:00      21      22      23      24
2020-01-01 07:00:00      25      26      27      28
2020-01-01 08:00:00      29      30      31      32
2020-01-01 09:00:00      33      34      35      36
2020-01-01 10:00:00      37      38      39      40

In [234]:
data_supervised = DP.data_to_supervised(data, n_in=3, n_out=2)
data_supervised

WDIR_1(t-3)  WSPD_2(t-3)  WDIR_3(t-3)  WSPD_4(t-3)  \
2020-01-01 04:00:00          1.0          2.0          3.0          4.0   
2020-01-01 05:00:00          5.0          6.0          7.0          8.0   
2020-01-01 06:00:00          9.0         10.0         11.0         12.0   
2020-01-01 07:00:00         13.0         14.0         15.0         16.0   
2020-01-01 08:00:00         17.0         18.0         19.0         20.0   
2020-01-01 09:00:00         21.0         22.0         23.0         24.0   

                     WDIR_1(t-2)  WSPD_2(t-2)  WDIR_3(t-2)  WSPD_4(t-2)  \
2020-01-01 04:00:00          5.0          6.0          7.0          8.0   
2020-01-01 05:00:00          9.0         10.0         11.0         12.0   
2020-01-01 06:00:00         13.0         14.0         15.0         16.0   
2020-01-01 07:00:00         17.0         18.0         19.0         20.0   
2020-01-01 08:00:00         21.0         22.0         23.0         24.0   
2020-01-01 09:00:00         25.0         26.0         27.0         28.0   

                     WDIR_1(t-1)  WSPD_2(t-1)  WDIR_3(t-1)  WSPD_4(t-1)  \
2020-01-01 04:00:00          9.0         10.0         11.0         12.0   
2020-01-01 05:00:00         13.0         14.0         15.0         16.0   
2020-01-01 06:00:00         17.0         18.0         19.0         20.0   
2020-01-01 07:00:00         21.0         22.0         23.0         24.0   
2020-01-01 08:00:00         25.0         26.0         27.0         28.0   
2020-01-01 09:00:00         29.0         30.0         31.0         32.0   

                     WDIR_1(t)  WSPD_2(t)  WDIR_3(t)  WSPD_4(t)  WDIR_1(t+1)  \
2020-01-01 04:00:00         13         14         15         16         17.0   
2020-01-01 05:00:00         17         18         19         20         21.0   
2020-01-01 06:00:00         21         22         23         24         25.0   
2020-01-01 07:00:00         25         26         27         28         29.0   
2020-01-01 08:00:00         29         30         31         32         33.0   
2020-01-01 09:00:00         33         34         35         36         37.0   

                     WSPD_2(t+1)  WDIR_3(t+1)  WSPD_4(t+1)  
2020-01-01 04:00:00         18.0         19.0         20.0  
2020-01-01 05:00:00         22.0         23.0         24.0  
2020-01-01 06:00:00         26.0         27.0         28.0  
2020-01-01 07:00:00         30.0         31.0         32.0  
2020-01-01 08:00:00         34.0         35.0         36.0  
2020-01-01 09:00:00         38.0         39.0         40.0

In [235]:
data_supervised.columns


Index(['WDIR_1(t-3)', 'WSPD_2(t-3)', 'WDIR_3(t-3)', 'WSPD_4(t-3)',
       'WDIR_1(t-2)', 'WSPD_2(t-2)', 'WDIR_3(t-2)', 'WSPD_4(t-2)',
       'WDIR_1(t-1)', 'WSPD_2(t-1)', 'WDIR_3(t-1)', 'WSPD_4(t-1)', 'WDIR_1(t)',
       'WSPD_2(t)', 'WDIR_3(t)', 'WSPD_4(t)', 'WDIR_1(t+1)', 'WSPD_2(t+1)',
       'WDIR_3(t+1)', 'WSPD_4(t+1)'],
      dtype='object')

In [267]:
# Input:
# Dataframe existing of columns that follow the following name convention:
# input values are marked with suffix: t-n
# output is marked with suffix: t or t+n
# depending on the suffix, the data is seperated into input (X) and output (y)
# Furthermore, the data is devided into train and test. The last n_test_hours rows represent the test set.
# Return:
#   train_X, test_X: numpy.array
#   train_y, test_y: pd.Dataframe

def train_test_split(data: pd.DataFrame, n_test_hours: int):
    # split into train and test sets
    train = data.head(-n_test_hours).values
    test = data.tail(n_test_hours).values

    # get indices of input and output columns
    input_cols = [i for i in range(data.values.shape[1]) if 't-' in data.columns[i]]
    output_cols = [i for i in range(data.values.shape[1]) if ('(t)' in data.columns[i]) or ('t+' in data.columns[i])]

    # split into input and outputs
    train_X, train_y = train[:, input_cols], train[:, output_cols]
    test_X, test_y = test[:, input_cols], test[:, output_cols]

    # reshape input to be 3D [samples, timesteps, features]
    train_X = train_X.reshape((train_X.shape[0], 1, train_X.shape[1]))
    test_X = test_X.reshape((test_X.shape[0], 1, test_X.shape[1]))

    return train_X, train_y, test_X, test_y

In [268]:
def train_test_split_2(data: pd.DataFrame, n_test_hours: int):

    # Extract time options
    input_cols, output_cols = [], []
    for column_header in data.columns:
        # Split the column header by '(' and ')' to extract the time option
        time_option = column_header.split('(')[-1].split(')')[0]
        time_option = f"({time_option})"
        if '-' in time_option and time_option not in input_cols:
            input_cols.append(time_option)
        elif '-' not in time_option and time_option not in output_cols:
                output_cols.append(time_option)

    # split into train and test sets
    train = data.head(-n_test_hours)
    test = data.tail(n_test_hours)

    #Create list of dataframes - one dataframe per time_stamp
    df_train_X, df_test_X, df_train_y, df_test_y = [], [], [], []
    for time_option in input_cols:
        df_train_X.append(train.filter(like=time_option, axis=1))
        df_test_X.append(test.filter(like=time_option, axis=1))

    for time_option in output_cols:
        df_train_y.append(train.filter(like=time_option, axis=1))
        df_test_y.append(test.filter(like=time_option, axis=1))

    # Get the dimensions
    train_X_dims = (df_train_X[0].shape[0], # Number of rows
                    len(df_train_X),        # Number of dataframes = number of timestamps
                    df_train_X[0].shape[1]     # number of cols = number of features
    )
    test_X_dims = (df_test_X[0].shape[0], # Number of rows
                    len(df_test_X),        # Number of dataframes = number of timestamps
                    df_test_X[0].shape[1]     # number of cols = number of features
    )
    train_y_dims = (df_train_y[0].shape[0], # Number of rows
                    len(df_train_y),        # Number of dataframes = number of timestamps
                    df_train_y[0].shape[1]     # number of cols = number of features
    )
    test_y_dims = (df_test_y[0].shape[0], # Number of rows
                    len(df_test_y),        # Number of dataframes = number of timestamps
                    df_test_y[0].shape[1]     # number of cols = number of features
    )

    # Create a three-dimensional array filled with NaN
    train_X = np.empty(train_X_dims)
    test_X  = np.empty(test_X_dims)
    train_y = np.empty(train_y_dims)
    test_y  = np.empty(test_y_dims)
    train_X.fill(np.nan)
    test_X.fill(np.nan)
    train_y.fill(np.nan)
    test_y.fill(np.nan)

    # Fill the array with data from dataframes
    for i, df in enumerate(df_train_X):
        train_X[:, i, :] = df.values
    for i, df in enumerate(df_test_X):
        test_X[:, i, :] = df.values
    for i, df in enumerate(df_train_y):
        train_y[:, i, :] = df.values
    for i, df in enumerate(df_test_y):
        test_y[:, i, :] = df.values

    return train_X, train_y, test_X, test_y

# STATUS:

the 3 dimensional shape should be as expected now ...

next goal:
    train / test split
    finalize this function
    then continue with CNN issue ...




In [269]:
train_X, train_y, test_X, test_y = train_test_split(data_supervised, 5)

In [270]:
print(train_X.shape)
train_X

(1, 1, 12)


array([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]])

In [271]:
print(train_y.shape)
train_y

(1, 8)


array([[13., 14., 15., 16., 17., 18., 19., 20.]])

In [272]:
print(test_X.shape)
test_X

(5, 1, 12)


array([[[ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.]],

       [[ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]],

       [[13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.]],

       [[17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.]],

       [[21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.]]])

In [273]:
print(test_y.shape)
test_y

(5, 8)


array([[17., 18., 19., 20., 21., 22., 23., 24.],
       [21., 22., 23., 24., 25., 26., 27., 28.],
       [25., 26., 27., 28., 29., 30., 31., 32.],
       [29., 30., 31., 32., 33., 34., 35., 36.],
       [33., 34., 35., 36., 37., 38., 39., 40.]])

In [143]:
# train_X_scaled, train_y_scaled, test_X_scaled, test_y_scaled, SCALER = DP.scale_data(train_X, train_y, test_X, test_y)

In [144]:
train_X.shape #Shouldn't it be (184053, 1, 312)

(22, 12)

In [260]:
# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, train_X.shape[2])))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [261]:
model.fit(train_X, train_y, epochs=1000, verbose=0)

In [22]:
#model = mL.Models.get_model("CNN", train_X, train_y, 0.0)
#model.summary()