# Predict water temperature using LSTM models

TODO:
* use the same data as for baseline model
* use only one variable and then all of than buoy to see improvement
* then use nearby buoys to see improvement

### References:

* https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/
* https://machinelearningmastery.com/time-series-forecasting-long-short-term-memory-network-python/
*

# Start with the Tutorial before using NDBC data:

# Univatiate One-Step Vanilla LSTM Model

The LSTM model will learn a function that maps a sequence of past observations as input to an output observation.

### Data preparation for LSTM model

In [7]:
# univariate data preparation
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [8]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()

    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)

    return array(X), array(y)

In [9]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
 print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [10]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

X

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

### Vanilla LSTM

In [11]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [12]:
# fit model
model.fit(X, y, epochs=200, verbose=0)

2023-04-10 18:25:12.429163: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


In [13]:
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)

yhat

array([[102.82197]], dtype=float32)